/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesNumbersRouteImport } from './routes/games/numbers'
import { Route as GamesColoursRouteImport } from './routes/games/colours'
import { Route as GamesAdjectivesRouteImport } from './routes/games/adjectives'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesNumbersRoute = GamesNumbersRouteImport.update({
  id: '/games/numbers',
  path: '/games/numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesColoursRoute = GamesColoursRouteImport.update({
  id: '/games/colours',
  path: '/games/colours',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesAdjectivesRoute = GamesAdjectivesRouteImport.update({
  id: '/games/adjectives',
  path: '/games/adjectives',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/adjectives': typeof GamesAdjectivesRoute
  '/games/colours': typeof GamesColoursRoute
  '/games/numbers': typeof GamesNumbersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/adjectives': typeof GamesAdjectivesRoute
  '/games/colours': typeof GamesColoursRoute
  '/games/numbers': typeof GamesNumbersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/adjectives': typeof GamesAdjectivesRoute
  '/games/colours': typeof GamesColoursRoute
  '/games/numbers': typeof GamesNumbersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games/adjectives' | '/games/colours' | '/games/numbers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games/adjectives' | '/games/colours' | '/games/numbers'
  id:
    | '__root__'
    | '/'
    | '/games/adjectives'
    | '/games/colours'
    | '/games/numbers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesAdjectivesRoute: typeof GamesAdjectivesRoute
  GamesColoursRoute: typeof GamesColoursRoute
  GamesNumbersRoute: typeof GamesNumbersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/numbers': {
      id: '/games/numbers'
      path: '/games/numbers'
      fullPath: '/games/numbers'
      preLoaderRoute: typeof GamesNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/colours': {
      id: '/games/colours'
      path: '/games/colours'
      fullPath: '/games/colours'
      preLoaderRoute: typeof GamesColoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/adjectives': {
      id: '/games/adjectives'
      path: '/games/adjectives'
      fullPath: '/games/adjectives'
      preLoaderRoute: typeof GamesAdjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesAdjectivesRoute: GamesAdjectivesRoute,
  GamesColoursRoute: GamesColoursRoute,
  GamesNumbersRoute: GamesNumbersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
